version: "3.8"
services:
  db:
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  api:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: "${PORT}"
      NODE_ENV: "${NODE_ENV}"
      BASE_URL: "${BASE_URL}"
      DB_PORT: "3306"
      DB_HOST: db
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      REDIS_PORT: "6379"
      REDIS_HOST: redis
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_TTL: "${REDIS_TTL}"
volumes:
  db:
    driver: local
  redis_data:
